import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { getSession, useSession, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  const handleSignOut = signOut();


  return (
    <div>
      <Head>
        <title>Auth-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? <User session={session} handleSignOut={handleSignOut}/> : <Guest />}
    </div>
  );
}

const Guest = () => {
  return (
    <main className="container mx-auto text-center py-20">
      <h1 className="text-4xl font-bold">Guest Homepage</h1>

      <div className="flex justify-center">
        <Link href="/login" className="mt-5">
          <span className="px-10 py-1 rounded-sm bg-indigo-500 text-white">
            Sign In
          </span>
        </Link>
      </div>
    </main>
  );
};

const User = ({ session, handleSignOut }) => {
  return (
    <main className="container mx-auto text-center py-20">
      <h1 className="text-4xl font-bold">User Homepage</h1>

      <div className="details">
        <h5>{session?.user.name}</h5>
        <h5>{session?.user.email}</h5>
      </div>

      <div className="flex justify-center">
        <button
          type="button"
          className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 text-gray-50"
          onClick={handleSignOut}
        >
          Sign Out
        </button>
      </div>

      <div className="flex justify-center">
        <Link href="/profile" className="mt-5">
          <span className="px-10 py-1 rounded-sm bg-indigo-500 text-white">
            Profile Page
          </span>
        </Link>
      </div>
    </main>
  );
};

export const getServerSideProps = async ({ req }) => {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    props: {
      session,
    },
  };
};
