import Head from "next/head";
import React from "react";

const Login = () => {
  return (
    <div>
      <Head>
        <title>Auth-app-login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Login
    </div>
  );
};

export default Login;
