import Head from "next/head";
import React, { useState } from "react";
import Layout from "../layout/layout";
import styles from "../styles/Form.module.css";
import { FcGoogle } from "react-icons/fc";
import { GoMarkGithub } from "react-icons/go";
import { HiAtSymbol, HiFingerPrint, HiOutlineUser } from "react-icons/hi";
import Link from "next/link";

const Register = () => {
  const [show, setShow] = useState({
    password : false,
    cpassword: false
  })

  return (
    <Layout>
      <Head>
        <title>Auth-app-login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-3/4 mx-auto flex flex-col gap-10">
        <div className="title">
          <h1 className="text-gray-800 text-4xl font-bold py-4">Register</h1>
          <p className="w-3/4 mx-auto text-gray-400">
            It is a long established fact that a reader will be distracted by
            the readable content of a page when looking at its layout.
          </p>
        </div>

        <form className="flex flex-col gap-5" action="submit">
          <div className={styles.input_group}>
            <input
              className={styles.input_text}
              type="text"
              name="Username"
              placeholder="User name"
            />
            <span className="icon flex items-center px-4">
              <HiOutlineUser size={25} />
            </span>
          </div>
          <div className={styles.input_group}>
            <input
              className={styles.input_text}
              type="email"
              name="email"
              placeholder="email"
            />
            <span className="icon flex items-center px-4">
              <HiAtSymbol size={25} />
            </span>
          </div>
          <div className={styles.input_group}>
            <input
              className={styles.input_text}
              type={show.password ? "text" : "password"}
              name="password"
              placeholder="password"
            />
            <span
              className="icon flex items-center px-4 hover:text-[#6366f1] cursor-pointer"
              onClick={() => setShow({...show, password: !show.password})}
            >
              <HiFingerPrint size={25} />
            </span>
          </div>
          <div className={styles.input_group}>
            <input
              className={styles.input_text}
              type={show.cpassword ? "text" : "password"}
              name="cpassword"
              placeholder="Confirm Password"
            />
            <span
              className="icon flex items-center px-4 hover:text-[#6366f1] cursor-pointer"
              onClick={() => setShow({...show, cpassword: !show.cpassword})}
            >
              <HiFingerPrint size={25} />
            </span>
          </div>
          <div className="input-button">
            <button type="submit" className={`${styles.button}`}>
              Login
            </button>
          </div>
        </form>
        <div className="text-center text-gray-400 flex justify-center gap-2">
          Have an account?
          <Link href="/login">

              <span className="text-blue-800 underline">Login</span>

          </Link>
        </div>
      </section>
    </Layout>
  );
};

export default Register;
